# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='address',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
