# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('purchaseCount', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('SPO', 'Sports'), ('RAC', 'Racing'), ('RPG', 'RPG'), ('ACT', 'Action'), ('ADV', 'Adventure'), ('CAS', 'Casual'), ('STR', 'Strategy'), ('OTH', 'Other')], max_length=3)),
                ('developerEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gamedata.Developer')),
            ],
            options={
                'ordering': ('purchaseCount',),
            },
        ),
        migrations.CreateModel(
            name='GamesOfPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highscore', models.PositiveIntegerField()),
                ('gameState', models.TextField()),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamesofplayer',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gamedata.Player'),
        ),
    ]
