# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-purchaseCount',)},
        ),
        migrations.AlterModelOptions(
            name='gamesofplayer',
            options={'ordering': ('-highscore',)},
        ),
        migrations.RemoveField(
            model_name='game',
            name='developerEmail',
        ),
        migrations.RemoveField(
            model_name='gamesofplayer',
            name='gameID',
        ),
        migrations.RemoveField(
            model_name='gamesofplayer',
            name='username',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gamedata.Developer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesofplayer',
            name='game',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='gamedata.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesofplayer',
            name='purchaseTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesofplayer',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gamedata.Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
